import turtle as t
t.speed()
def x11():
    t.speed(45)
    t.color("brown")
    t.penup()
    t.goto(-80, 160)
    t.pendown()
    t.left(155)
    t.forward(15)
    t.pendown()
    t.goto(-80, 160)
    t.pendown()
    t.left(360)
    t.forward(-15)
    t.pendown()
    t.goto(-80, 160)
    t.pendown()
    t.right(100)
    t.forward(15)
    t.pendown()
    t.goto(-80, 160)
    t.pendown()
    t.left(180)
    t.forward(15)
    t.pendown()

def x12():
    t.speed(45)
    t.color("brown")
    t.penup()
    t.goto(0, 160)
    t.pendown()
    t.left(155)
    t.forward(15)
    t.pendown()
    t.goto(0, 160)
    t.pendown()
    t.left(360)
    t.forward(-15)
    t.pendown()
    t.goto(0, 160)
    t.pendown()
    t.right(100)
    t.forward(15)
    t.pendown()
    t.goto(0, 160)
    t.pendown()
    t.left(180)
    t.forward(15)
    t.pendown()

def x13():
    t.speed(45)
    t.color("brown")
    t.penup()
    t.goto(80, 160)
    t.pendown()
    t.left(155)
    t.forward(15)
    t.pendown()
    t.goto(80, 160)
    t.pendown()
    t.left(360)
    t.forward(-15)
    t.pendown()
    t.goto(80, 160)
    t.pendown()
    t.right(100)
    t.forward(15)
    t.pendown()
    t.goto(80, 160)
    t.pendown()
    t.left(180)
    t.forward(15)
    t.pendown()

def x21():
    t.speed(45)
    t.color("brown")
    t.penup()
    t.goto(-80, 80)
    t.pendown()
    t.left(155)
    t.forward(15)
    t.pendown()
    t.goto(-80, 80)
    t.pendown()
    t.left(360)
    t.forward(-15)
    t.pendown()
    t.goto(-80, 80)
    t.pendown()
    t.right(100)
    t.forward(15)
    t.pendown()
    t.goto(-80, 80)
    t.pendown()
    t.left(180)
    t.forward(15)
    t.pendown()

def x22():
    t.speed(45)
    t.color("brown")
    t.penup()
    t.goto(-0, 80)
    t.pendown()
    t.left(155)
    t.forward(15)
    t.pendown()
    t.goto(-0, 80)
    t.pendown()
    t.left(360)
    t.forward(-15)
    t.pendown()
    t.goto(-0, 80)
    t.pendown()
    t.right(100)
    t.forward(15)
    t.pendown()
    t.goto(-0, 80)
    t.pendown()
    t.left(180)
    t.forward(15)
    t.pendown()

def x23():
    t.speed(45)
    t.color("brown")
    t.penup()
    t.goto(80, 80)
    t.pendown()
    t.left(155)
    t.forward(15)
    t.pendown()
    t.goto(80, 80)
    t.pendown()
    t.left(360)
    t.forward(-15)
    t.pendown()
    t.goto(80, 80)
    t.pendown()
    t.right(100)
    t.forward(15)
    t.pendown()
    t.goto(80, 80)
    t.pendown()
    t.left(180)
    t.forward(15)
    t.pendown()

def x31():
    t.speed(45)
    t.color("brown")
    t.penup()
    t.goto(-80, 0)
    t.pendown()
    t.left(155)
    t.forward(15)
    t.pendown()
    t.goto(-80, 0)
    t.pendown()
    t.left(360)
    t.forward(-15)
    t.pendown()
    t.goto(-80, 0)
    t.pendown()
    t.right(100)
    t.forward(15)
    t.pendown()
    t.goto(-80, 0)
    t.pendown()
    t.left(180)
    t.forward(15)
    t.pendown()

def x32():
    t.speed(45)
    t.color("brown")
    t.penup()
    t.goto(-0, 0)
    t.pendown()
    t.left(155)
    t.forward(15)
    t.pendown()
    t.goto(-0, 0)
    t.pendown()
    t.left(360)
    t.forward(-15)
    t.pendown()
    t.goto(-0, 0)
    t.pendown()
    t.right(100)
    t.forward(15)
    t.pendown()
    t.goto(-0, 0)
    t.pendown()
    t.left(180)
    t.forward(15)
    t.pendown()

def x33():
    t.speed(45)
    t.color("brown")
    t.penup()
    t.goto(80, 0)
    t.pendown()
    t.left(155)
    t.forward(15)
    t.pendown()
    t.goto(80, 0)
    t.pendown()
    t.left(360)
    t.forward(-15)
    t.pendown()
    t.goto(80, 0)
    t.pendown()
    t.right(100)
    t.forward(15)
    t.pendown()
    t.goto(80, 0)
    t.pendown()
    t.left(180)
    t.forward(15)
    t.pendown()

if __name__=="__main__":
    x11()
    x12()
    x13()
    x21()
    x22()
    x23()
    x31()
    x32()
    x33()